export type BookCandidate={id:string;title:string;author?:string;cover_url?:string;description?:string;publisher?:string;publish_year?:number;isbn?:string;total_pages?:number};
import {pythonProxy} from './python-proxy';
export interface BookMetadataProvider{searchBooks(query:string):Promise<BookCandidate[]>;getBookDetail(id:string):Promise<BookCandidate|null>;enrichBook(book:BookCandidate):Promise<BookCandidate>}
const fetchWithTimeout=(url:string)=>fetch(url,{signal:AbortSignal.timeout(8000),headers:{accept:'application/json'}});
export class OpenLibraryProvider implements BookMetadataProvider{async searchBooks(query:string){const d=await pythonProxy({kind:'openlibrary',query});return (d.docs||[]).map((x:any)=>({id:x.key,title:x.title,author:x.author_name?.[0],publish_year:x.first_publish_year,isbn:x.isbn?.[0],publisher:x.publisher?.[0]}))}async getBookDetail(id:string){return null}async enrichBook(book:BookCandidate){return book}}
export class GoogleBooksProvider implements BookMetadataProvider{async searchBooks(query:string){const d=await pythonProxy({kind:'books',query});return (d.items||[]).map((x:{id:string;volumeInfo?:any})=>({id:`google-${x.id}`,title:x.volumeInfo?.title||query,author:x.volumeInfo?.authors?.[0],publish_year:x.volumeInfo?.publishedDate?Number(x.volumeInfo.publishedDate.slice(0,4)):undefined,description:x.volumeInfo?.description,publisher:x.volumeInfo?.publisher,cover_url:x.volumeInfo?.imageLinks?.thumbnail,isbn:x.volumeInfo?.industryIdentifiers?.[0]?.identifier}))}async getBookDetail(){return null}async enrichBook(book:BookCandidate){return book}}
export class FallbackBookMetadataProvider implements BookMetadataProvider{async searchBooks(_query:string){return []}async getBookDetail(_id:string){return null}async enrichBook(book:BookCandidate){return book}}
export class ResilientBookMetadataProvider implements BookMetadataProvider{private fallback=new FallbackBookMetadataProvider();private remote=new OpenLibraryProvider();private secondary=new GoogleBooksProvider();async searchBooks(q:string){try{const r=await this.remote.searchBooks(q);if(r.length)return r}catch{}try{const r=await this.secondary.searchBooks(q);if(r.length)return r}catch{}return this.fallback.searchBooks(q)}async getBookDetail(id:string){return this.fallback.getBookDetail(id)}async enrichBook(b:BookCandidate){return b}}
export const bookMetadataProvider:BookMetadataProvider=new ResilientBookMetadataProvider();
